# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: false

before_install:
  Rscript -e 'update.packages(ask = FALSE)'

after_script:
  - "curl --request POST --form token=d8d69ec8f7941263cf1f9d1105292e698b803fce --form ref=master https://api.travis-ci.org/repo/chschan%2FtestCI/requests"
